#!/usr/bin/env bash

if [ ! -d ~/.composer ]; then
	mkdir ~/.composer
	echo "Directory \"~/.composer\" created. (Cached files will be stored there)"
fi

docker run --rm -v $(pwd):/app -v ~/.composer:/composer-data -e "COMPOSER_HOME=/composer-data" composer/composer $1