#!/usr/bin/env bash

if [ ! -d ~/.composer ]; then
	mkdir ~/.composer
	echo "Directory \"~/.composer\" created. (Cached files will be stored there)"
fi

docker run --rm --net=host -it -v $(pwd):/app -v ~/.composer:/composer -v ~/.ssh:/root/.ssh composer $@
