#!/usr/bin/env bash

if [ ! -d ~/.npm ]; then
	mkdir ~/.npm
	echo "Directory \"~/.npm\" created. (Cached files will be stored there)"
fi

docker run --rm --net=host -it -v $(pwd):/app -v ~/.ssh:/root/.ssh -v ~/.npm:/npm-data -e "NPM_CONFIG_CACHE=/npm-data" furdarius/npm-hard-docker $@